# Generated by Django 4.2.16 on 2024-11-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NOTICE', '공지'), ('FREE', '자유'), ('QUESTION', '질문'), ('RECOMMEND', '추천')], default='FREE', max_length=20),
        ),
    ]
