# Generated by Django 4.2.16 on 2024-11-21 00:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'base_products',
            },
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.baseproduct')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('save_trm', models.IntegerField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate2', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('join_way', models.TextField()),
                ('join_member', models.TextField()),
                ('etc_note', models.TextField()),
            ],
            options={
                'db_table': 'deposit_products',
            },
        ),
        migrations.CreateModel(
            name='RentHouseLoan',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.baseproduct')),
                ('loan_rate_type', models.CharField(max_length=100)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_loan_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_period', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('repayment_type', models.CharField(max_length=100)),
                ('requirement', models.TextField()),
                ('guarantee_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rent_house_loans',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', '유지중'), ('EXPIRED', '만기'), ('CANCELED', '해지')], default='ACTIVE', max_length=20)),
                ('product_type', models.CharField(choices=[('DEPOSIT', '정기예금'), ('RENT_LOAN', '전세자금대출')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_users', to='products.baseproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_products',
            },
        ),
    ]
