# Generated by Django 4.2.16 on 2024-11-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
